---
title: "Stats 111 Homework 1"
author: "Owen Lin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(epitools)
library(rmeta)
library(pROC)
library(nnet)
```


HW Scratch
```{r}
prop.comp <- function( x, estimate="all", conf.level=.95, transpose=FALSE ){
	if( transpose ) x <- t(x)
	rslt <- vector( "list", length=3 )
	names( rslt ) <- c( "riskdiff", "riskratio", "oddsratio" )
	diff.rslt <- suppressWarnings(prop.test( x, conf.level=conf.level ))
	rslt[[1]] <- rslt[[2]] <- rslt[[3]] <- epitab( x, method="riskratio", pvalue="chi2", conf.level=conf.level )$tab
	colnames( rslt[[1]] )[5] <- "riskdiff"
	rslt[[1]][,5] <- c(0,diff(rev(diff.rslt$estimate)))
	rslt[[1]][2,6:7] <- diff.rslt$conf.int
	colnames( rslt[[3]] )[5] <- "oddsratio"
	rslt[[3]][,5:8] <- suppressWarnings(epitab( x, method="oddsratio", pvalue="chi2", conf.level=conf.level )$tab[,5:8])
	if(is.null(names(dimnames(x)))){
		for(i in 1:3){
			colnames(rslt[[i]])[c(1,3)] <- c("Outcome=0", "Outcome=1")
			rownames(rslt[[i]]) <- c("Group=1", "Group=2")
			}
	}
	if( is.element( estimate, c("all", "oddsratio") ) ){ 
		if(is.null(names(dimnames(x)))){
			warning( "Estimated probabilities represent Pr[ Outcome | Group ]. For estimates of 
			Pr[ Group | Outcome ], change the value of 'transpose'.")
		}
		else
			warning( paste("Estimated probabilities represent Pr[", names(dimnames(x))[2], 
			"|",names(dimnames(x))[1], "]. For estimates of 
			Pr[", names(dimnames(x))[1], "|",names(dimnames(x))[2], "], change the value of 'transpose'.") )
		}
	if( estimate == "riskdiff" ) return(rslt[[1]])
	else if( estimate == "riskratio" ) return(rslt[[2]])
	else if( estimate == "oddsratio" ) return(rslt[[3]])
	else return(rslt)
}
```

```{r}
# 2
chisq.test(c(300, 192, 8), p = c(0.75, 0.24, 0.01))

```

```{r}
# 3
std_dat <- matrix(c(140L, 200L, 60L, 50L),
                  nrow = 2, ncol = 2,
                  dimnames = list(
                    c("low", "high"),
                    c("no", "yes")))
print(std_dat)
prop.comp(std_dat)



# chisq.test(x = c(300, 150, 50), y = c(0.75, 0.24, 0.01))
# ?chisq.test()
```

```{r}
# 4
smoke <- matrix(data = c(1168, 188, 1823, 416, 1380, 400), 
						3, 2,
				byrow = TRUE,
                dimnames = list(
                 c("No", "one", "both"),
                 c("No smoke", "smoke")))
addmargins(smoke) # View two-way contingency table with totals

1356*1004/5375
chisq.test(smoke, correct = FALSE)
```

```{r}
# 6
Urso <- matrix(c(92, 87, 8, 23),
                  nrow = 2, ncol = 2,
                  dimnames = list(
                    c("placebo", "Urso"),
                    c("neg", "pos")))
print(Urso)
prop.comp(Urso)


n1 = 110
n0 = 100
p1 = 23/110
p0 = 8/100
RD = p1-p0
RR = p1/p0
lnRR = log(RR)
OR = (p1/(1-p1))/(p0/(1-p0))
lnOR = log(OR)
```

```{r}
#6b
seRD = (p1*(1-p1)/n1 + p0*(1-p0)/n0)^0.5
seRD
RDlowCI = RD - 1.96*seRD
RDlowCI
RDhighCI = RD + 1.96*seRD
RDhighCI


selnRR = ((1-p1)/p1/n1 + (1-p0)/p0/n0)^0.5
selnRR
lnRRlowCI = lnRR - 1.96*selnRR
lnRRlowCI
lnRRhighCI = lnRR + 1.96*selnRR
lnRRhighCI


selnOR = (1/p1/n1 + 1/(1-p1)/n1 + 1/p0/n0 + 1/(1-p0)/n0)^0.5
selnOR
lnORlowCI = lnOR - 1.96*selnOR
lnORlowCI
lnORhighCI = lnOR + 1.96*selnOR
lnORhighCI
```